build_script:
  - gradlew.bat shadowJar --no-daemon --stacktrace

test_script:
  - gradlew.bat check --stacktrace -PlogTests -Pheadless

shallow_clone: true

on_success:
  - 'del /f %USERPROFILE%\.gradle\caches\modules-2\modules-2.lock'

cache:
  - '%USERPROFILE%\.gradle\caches -> **\*.gradle.kts'
  - '%USERPROFILE%\.gradle\wrapper -> **\*.gradle.kts'
  - '%USERPROFILE%\.m2 -> **\*.gradle.kts'
