# NOTE: Don't use `sudo` anywhere or the build will run on Travis's slower, outdated build system
language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
#    - os: osx
#      osx_image: xcode8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-installer
      - libstdc++-4.9-dev

before_install:
  - if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    fi

script:
  - ./gradlew check --stacktrace -PlogTests -Pheadless

after_success:
  - if [[ $TRAVIS_OS_NAME != 'osx' ]]; then bash <(curl -s https://codecov.io/bash); fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
